import { useState } from 'react'
import { BrowserRouter, Link, Route, Routes, useParams } from 'react-router-dom'
import { ArrowUpRight, ChevronRight, Footprints, MapPin, Menu, Moon, Store, Sun, X } from 'lucide-react'
import { projects } from './data/projects'
import { tools } from './data/tools'
import './styles.css'

const highlightIcons = { store: Store, shoe: Footprints, location: MapPin }

function Nav({ dark, setDark }) {
  const [open, setOpen] = useState(false)
  const items = [['Sobre mí', 'sobre-mi'], ['Herramientas', 'herramientas'], ['Proyectos', 'proyectos'], ['Contacto', 'contacto']]
  return <header className="nav"><Link className="brand" to="/">LZ<span>.</span><small>DATA ANALYST</small></Link><button className="menu-btn" onClick={() => setOpen(!open)} aria-label="Abrir menú">{open ? <X /> : <Menu />}</button><nav className={open ? 'links open' : 'links'}>{items.map(([label, id]) => <a key={id} href={`/#${id}`} onClick={() => setOpen(false)}>{label}</a>)}<button className="theme" onClick={() => setDark(!dark)} aria-label="Cambiar tema">{dark ? <Sun /> : <Moon />}</button></nav></header>
}

function Footer() { return <footer><span>© 2024 Lucas Zelaya</span><a href="https://www.linkedin.com/in/lucas-zelaya" target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight /></a><a href="#inicio">Volver arriba ↑</a></footer> }
function ProjectCard({ project, index }) { return <Link className={`project-card p${index}`} to={`/projects/${project.id}`}><div className="project-image"><img src={project.image} alt={`Vista previa de ${project.title}`} /><span className="project-index">0{index + 1}</span></div><div className="project-meta"><div><span className="eyebrow">{project.eyebrow}</span><h3>{project.title}</h3><p>{project.description}</p></div><ArrowUpRight className="arrow" /></div><div className="tags">{project.tools.map(tool => <span key={tool}>{tool}</span>)}<span>{project.year}</span></div></Link> }
function Home() { return <><section className="hero" id="inicio"><p className="kicker">Disponible para nuevos proyectos <i /></p><h1>Lucas Zelaya<br /><em>Data Analyst.</em></h1><div className="hero-bottom"><p>Analista de datos enfocado en transformar preguntas complejas en decisiones simples, visuales y accionables.</p><div className="hero-actions"><a className="outline-btn" href="#proyectos">Ver proyectos <ChevronRight /></a><a className="outline-btn secondary-btn" href="/cv.pdf" target="_blank" rel="noreferrer">Ver CV <ArrowUpRight /></a></div></div><div className="scroll">SCROLL TO EXPLORE <span>↓</span></div></section><section className="intro section" id="sobre-mi"><div className="section-label">01 / SOBRE MÍ</div><div className="intro-copy"><p className="large-copy">Trabajo entre la curiosidad y la precisión. Mi objetivo es encontrar la señal importante dentro del ruido.</p><p>Combino pensamiento analítico, diseño de información y herramientas de visualización para que los equipos puedan ver mejor, preguntar mejor y actuar con confianza.</p><a className="text-link" href="#contacto">Hablemos <ArrowUpRight /></a></div></section><section className="tools section" id="herramientas"><div className="section-label">02 / HERRAMIENTAS</div><div className="tool-grid">{tools.map(tool => <div className="tool" key={tool.id}><span>{tool.number}</span><h3>{tool.name}</h3><p>{tool.description}</p></div>)}</div></section><section className="work section" id="proyectos"><div className="work-head"><div className="section-label">03 / PROYECTOS</div><p>Una selección de trabajos recientes<br />y preguntas que vale la pena explorar.</p></div><div className="project-grid">{projects.map((p, i) => <ProjectCard key={p.id} project={p} index={i} />)}</div></section><section className="contact section" id="contacto"><div className="section-label">04 / CONTACTO</div><div><h2>Contacta<br /><em>conmigo.</em></h2><a className="solid-btn" href="mailto:hola@alexrivera.com">Contáctame <ArrowUpRight /></a></div></section><Footer /></> }
function Detail() { const { id } = useParams(); const p = projects.find(x => x.id === id); if (!p) return <main className="not-found"><h1>Proyecto no encontrado.</h1><Link to="/">Volver al inicio</Link></main>; return <><main className="detail"><Link className="back" to="/">← Volver a proyectos</Link><section className="detail-hero"><div className="detail-heading"><span className="eyebrow">{p.eyebrow} / {p.year}</span><h1>{p.title}</h1><p>{p.description}</p></div><img className="detail-hero-image" src={p.image} alt={`Imagen principal de ${p.title}`} /></section><section className="case-section objective"><div className="section-label">01 / OBJETIVO</div><div className="detail-body"><p className="large-copy">{p.detail}</p><div className="detail-side"><span className="section-label">HERRAMIENTAS</span><div className="tags">{p.tools.map(t => <span key={t}>{t}</span>)}</div></div></div></section>{p.dashboard?.length > 0 && <section className="case-section dashboard-section"><div className="section-label">02 / DASHBOARD</div><p className="section-intro">Vistas principales del dashboard y las preguntas que ayudan a responder.</p><div className="dashboard-list">{p.dashboard.map(item => <article className="dashboard-view" key={item.number}><div className="dashboard-copy"><span>{item.number}</span><h2>{item.title}</h2><p>{item.description}</p></div><img src={item.image} alt={`${item.title} — ${p.title}`} /></article>)}</div></section>}{p.highlights?.length > 0 && <section className="case-section highlights-section"><div className="section-label">03 / PRINCIPALES HALLAZGOS</div><div className="highlight-grid">{p.highlights.map(item => { const Icon = highlightIcons[item.icon] || Store; return <article className="highlight" key={item.title}><Icon className="highlight-icon" /><h3>{item.title}</h3><p>{item.description}</p><strong>{item.value}</strong><small>{item.secondaryValue}</small></article> })}</div></section>}{p.conclusion && <section className="case-section conclusion"><div className="section-label">04 / CONCLUSIÓN</div><p className="large-copy">{p.conclusion}</p></section>}{p.documentation && <section className="case-section documentation"><div className="section-label">05 / DOCUMENTACIÓN</div><a className="solid-btn" href={p.documentation} target="_blank" rel="noreferrer">Ver documentación <ArrowUpRight /></a></section>}</main><Footer /></> }
function App() { const [dark, setDark] = useState(true); return <div className={dark ? 'app dark' : 'app'} data-theme={dark ? 'dark' : 'light'}><Nav dark={dark} setDark={setDark} /><Routes><Route path="/" element={<Home />} /><Route path="/projects/:id" element={<Detail />} /></Routes></div> }
export default function Root() { return <BrowserRouter><App /></BrowserRouter> }
